export const RECOMMEND_DATA = [
  {
    id: 1,
    description: 'Top 10 places to visit in Norway this summer',
    image:
      'https://images.unsplash.com/photo-1527004013197-933c4bb611b3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'easy',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 2,
    description: 'Best forests to visit in North America',
    image:
      'https://images.unsplash.com/photo-1448375240586-882707db888b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 3,
    description: 'Hawaii beaches review: better than you think',
    image:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'hard',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 4,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 5,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 6,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
]
export const PROBLEM_DATA = [
  {
    id: 1,
    description: 'Top 10 places to visit in Norway this summer',
    image:
      'https://images.unsplash.com/photo-1527004013197-933c4bb611b3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'easy',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 2,
    description: 'Best forests to visit in North America',
    image:
      'https://images.unsplash.com/photo-1448375240586-882707db888b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 3,
    description: 'Hawaii beaches review: better than you think',
    image:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'hard',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 4,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 5,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 6,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 7,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 8,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 9,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 10,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 11,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 12,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 13,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 14,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 15,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
  {
    id: 16,
    description: 'Mountains at night: 12 best locations to enjoy the view',
    image:
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80',
    price: 58000,
    difficulty: 'normal',
    tag: ['#태그1', '#태그2'],
    code: 'C0Q1X',
    data: {
      problem: '문제어쩌고저쩌고',
      solution: '해설 어쩌고저쩌고',
      answer: 3,
      tag: '#수열의 귀납적 정의, #곡선으로 정의된 수열, #교점 찾기, #케이스 분류, #등차수열, #등차수열의 합, #그래프로 정의된 수열',
    },
  },
]
